#!/bin/bash

if [[ ! -d scripts ]]; then
    echo "Run script from the top of the repo."
    echo "sudo bash build-all"
    exit 1
fi

if [[ "$USER" != "root" ]]; then
    echo "Please run the script as super user."
    exit 1
fi

cd scripts

for script in [0-9][0-9][0-9]-* ; do
    echo "Launching ${script}..."
    ./${script} || exit $?
    echo ""
done

echo "Completed!"

