#!/bin/bash

# Install script for Chromium Browser.
# https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta

basepath=$( realpath $( dirname "$0" )/../ )

if [[ "$USER" == "root" ]]; then
    echo "Please run the script as a normal user, exiting..."
    exit 1
fi

# Test sudo; exit if wrong password or terminated via Ctrl-C.
sudo id >/dev/null; [[ $? -ne 0 ]] && exit 2

# Install package.
dpkg-query -f '${binary:Package}\n' -W | grep -q '^chromium-browser$'

if [[ $? -eq 1 ]]; then
    set -x  # enable verbose output

    # First uninstall Chromium, if it is installed, as it can conflict with chromium-browser.
    sudo apt-get autoremove -y --purge chromium ungoogled-chromium

    # Install curl.
    count=$( dpkg-query -f '${binary:Package}\n' -W | \
        egrep -c '^(curl|apt-transport-https|software-properties-common)$' )

    if [[ $count -ne 3 ]]; then
        sudo apt update -y
        sudo apt install -y curl apt-transport-https software-properties-common
    fi

    # Add the public key and repository.
    sudo add-apt-repository --yes --no-update ppa:saiarcot895/chromium-beta

    # Pin the PPA with a priority of 700.
    printf "Package: *\nPin: release o=LP-PPA-saiarcot895-chromium-beta\nPin-Priority: 700\n" \
        > /etc/apt/preferences.d/chromium-beta

    # Installation.
    sudo apt update -y
    sudo apt install -y chromium-browser

    set +x  # disable verbose output
fi

app=chromium-browser

# Install run script.
if [[ ! -f ~/bin/run-${app} ]]; then
    mkdir -p ~/bin
    cp -v "${basepath}/bin/run-${app}" ~/bin/.
fi

# Install desktop file.
if [[ ! -f ~/.local/share/applications/${app}.desktop ]]; then
    mkdir -p ~/.local/share/applications
    cp -v "${basepath}/desktop/${app}.desktop" ~/.local/share/applications/.
fi

echo "OK"

