#!/usr/bin/env bash

# Install script for Vivaldi.
# https://www.ubuntuupdates.org/ppa/opera

basepath=$( realpath $( dirname "$0" )/../ )

if [[ "$USER" == "root" ]]; then
    echo "Please run the script as a normal user, exiting..."
    exit 1
fi

# Test sudo; exit if wrong password or terminated via Ctrl-C.
sudo id >/dev/null; [[ $? -ne 0 ]] && exit 2

# Install package.
dpkg-query -f '${binary:Package}\n' -W | grep -q '^opera$'

if [[ $? -eq 1 ]]; then
    set -x  # enable verbose output

    # Install curl.
    count=$( dpkg-query -f '${binary:Package}\n' -W | \
        egrep -c '^(curl|apt-transport-https|software-properties-common)$' )

    if [[ $count -ne 3 ]]; then
        sudo apt update -y
        sudo apt install -y curl apt-transport-https software-properties-common
    fi

    # Add the public key and repository.
    curl -s https://deb.opera.com/archive.key | gpg --dearmor | \
        sudo tee /etc/apt/trusted.gpg.d/opera.gpg >/dev/null

    listfile=/etc/apt/sources.list.d/opera-stable.list

    sudo sh -c "echo \
        'deb https://deb.opera.com/opera-stable/ stable non-free' \
        >> $listfile"

    sudo sort -u $listfile -o $listfile

    # Installation.
    sudo apt update -y
    sudo apt install -y opera-stable

    set +x  # disable verbose output
fi

app=opera

# Install run script.
if [[ ! -f ~/bin/run-${app} ]]; then
    mkdir -p ~/bin
    cp -v "${basepath}/bin/run-${app}" ~/bin/.
fi

# Install desktop file.
if [[ ! -f ~/.local/share/applications/${app}.desktop ]]; then
    mkdir -p ~/.local/share/applications
    cp -v "${basepath}/desktop/${app}.desktop" ~/.local/share/applications/.
fi

echo "OK"

