#!/bin/bash

# Install script for Vivaldi.
# https://www.ubuntuupdates.org/ppa/opera

basepath=$( realpath $( dirname "$0" )/../ )

if [[ "$USER" == "root" ]]; then
    echo "Please run the script as a normal user, exiting..."
    exit 1
fi

# Test sudo; exit if wrong password or terminated via Ctrl-C.
sudo id >/dev/null; [[ $? -ne 0 ]] && exit 2

# Install package.
dpkg-query -f '${binary:Package}\n' -W | grep -q '^opera$'

if [[ $? -eq 1 ]]; then
    set -x  # enable verbose output

    # Install curl.
    count=$( dpkg-query -f '${binary:Package}\n' -W | \
        egrep -c '^(curl|apt-transport-https|software-properties-common)$' )

    if [[ $count -ne 3 ]]; then
        sudo apt update -y
        sudo apt install -y curl apt-transport-https software-properties-common
    fi

    # Add the public key and repository.
    curl -s https://deb.opera.com/archive.key | gpg --dearmor | \
        sudo tee /etc/apt/trusted.gpg.d/opera.gpg >/dev/null

    listfile=/etc/apt/sources.list.d/opera-stable.list

    sudo sh -c "echo \
        'deb https://deb.opera.com/opera-stable/ stable non-free' \
        >> $listfile"

    sudo sort -u $listfile -o $listfile

    # Add the public key and repository for "bionic" chromium-team-beta.
    # So that installing chromium-codecs-ffmpeg-extra from bionic versus focal.
    # The bionic package provides aac/ac3/mpeg4audio/h264/mov/mp3 codecs, missing in focal.

    curl -s 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xea6e302dc78cc4b087cfc3570ebea9b02842f111' | \
        gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/chromium-team.gpg >/dev/null

    listfile=/etc/apt/sources.list.d/chromium-team-beta.list

    sudo sh -c "echo \
        'deb http://ppa.launchpad.net/chromium-team/beta/ubuntu bionic main' \
        >> $listfile"

    sudo sort -u $listfile -o $listfile

    printf "Package: chromium-codecs-ffmpeg-extra\nPin: release n=bionic\nPin-Priority: 900\n" | \
        sudo tee /etc/apt/preferences.d/chromium-team-beta.pref >/dev/null

    # Installation.
    sudo apt update -y
    sudo apt install -y opera-stable

    # Make a symbolic link to libffmpeg.so inside lib_extra.
    sudo mkdir -p /usr/lib/x86_64-linux-gnu/opera/lib_extra
    sudo ln -sf /usr/lib/chromium-browser/libffmpeg.so /usr/lib/x86_64-linux-gnu/opera/lib_extra/libffmpeg.so

    set +x  # disable verbose output
fi

app=opera

# Install run script.
if [[ ! -f ~/bin/run-${app} ]]; then
    mkdir -p ~/bin
    cp -v "${basepath}/bin/run-${app}" ~/bin/.
fi

# Install desktop file.
if [[ ! -f ~/.local/share/applications/${app}.desktop ]]; then
    mkdir -p ~/.local/share/applications
    cp -v "${basepath}/desktop/${app}.desktop" ~/.local/share/applications/.
fi

echo "OK"

