#!/bin/bash

# Exit if nvidia-settings is not installed.
if [[ ! -f /usr/bin/nvidia-settings ]]; then
    echo "$0: package nvidia-settings is not installed, skipping..."
    exit 0
fi

# Exit if the the graphics driver does not meet requirement.
version=$(/usr/bin/nvidia-settings --version | grep version)
version=${version##* } # extract the version string from the line
version=${version%%.*} # extract major, not minor and revision

if [[ $(bc -l <<< "${version} < 470") -eq 1 ]]; then
    echo "$0: NVIDIA graphics driver is older than 470, skipping..."
    exit 0
fi

nvver="11.1.5.1"
echo "building nv-codec-headers"

mkdir -p builddir && cd builddir
rm -fr "nv-codec-headers-${nvver}"

if [[ ! -f nv-codec-headers-${nvver}.tar.gz ]]; then
    url="https://github.com/FFmpeg/nv-codec-headers/releases/download/n${nvver}/nv-codec-headers-${nvver}.tar.gz"
    echo "curl -LO ${url}"
    curl -LO ${url}
fi

tar xzf nv-codec-headers-${nvver}.tar.gz

if [[ -d nv-codec-headers-${nvver} ]]; then
    cd nv-codec-headers-${nvver}
    make PREFIX=/usr/local && \
    make install
fi

