#!/bin/bash

# Exit if the graphics driver is not installed.
if [[ ! -f /usr/bin/nvidia-settings ]]; then
    echo "$0: package nvidia-settings is not installed, skipping..."
    exit 0
fi

echo "building nv-codec-headers"

version=`/usr/bin/nvidia-settings --version | grep version`
version=${version##* } # extract the version string from the line
version=`echo $version | cut -d. -f1-2` # want major and minor, not revision

if   [[ $(bc -l <<< "${version} >= 470.57") -eq 1 ]]; then
    nvver="11.1.5.1"
elif [[ $(bc -l <<< "${version} >= 455.28") -eq 1 ]]; then
    nvver="11.0.10.0"
elif [[ $(bc -l <<< "${version} >= 445.87") -eq 1 ]]; then
    nvver="10.0.26.1"
elif [[ $(bc -l <<< "${version} >= 435.21") -eq 1 ]]; then
    nvver="9.1.23.2"
elif [[ $(bc -l <<< "${version} >= 418.30") -eq 1 ]]; then
    nvver="9.0.18.4"
elif [[ $(bc -l <<< "${version} >= 410.48") -eq 1 ]]; then
    nvver="8.2.15.11"
else
    echo "$0: NVIDIA graphics driver is older than 410.48, skipping..."
    exit 0
fi

mkdir -p builddir && cd builddir
rm -fr "nv-codec-headers-${nvver}"

if [[ ! -f nv-codec-headers-${nvver}.tar.gz ]]; then
    url="https://github.com/FFmpeg/nv-codec-headers/releases/download/n${nvver}/nv-codec-headers-${nvver}.tar.gz"
    echo "curl -LO ${url}"
    curl -LO ${url}
fi

tar xzf nv-codec-headers-${nvver}.tar.gz

if [[ -d nv-codec-headers-${nvver} ]]; then
    cd nv-codec-headers-${nvver}
    make PREFIX=/usr/local && make install
fi

