#!/bin/bash

# Uninstall script for Chromium Browser.
# https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta

if [[ "$USER" == "root" ]]; then
    echo "Please run the script as a normal user, exiting..."
    exit 1
fi

# Test sudo; exit if wrong password or terminated via Ctrl-C.
sudo id >/dev/null; [[ $? -ne 0 ]] && exit 2

# Remove desktop file.
rm -fv ~/.local/share/applications/chromium-browser.desktop

# Uninstall package.
dpkg-query -f '${binary:Package}\n' -W | grep -q '^chromium-browser$'

if [[ $? -eq 0 ]]; then
    set -x  # enable verbose output
    sudo apt autoremove -y --purge chromium-browser
    set +x  # disable verbose output
fi

# Remove apt files.
sudo rm -fv /etc/apt/sources.list.d/saiarcot895-*-chromium-beta-*.list
sudo rm -fv /etc/apt/trusted.gpg.d/saiarcot895_*_chromium-beta.gpg
sudo rm -fv /etc/apt/preferences.d/chromium-beta

echo "OK"

