#!/bin/bash

# Uninstall script for Google Chrome.
# https://www.ubuntuupdates.org/ppa/google_chrome

if [[ "$USER" == "root" ]]; then
    echo "Please run the script as a normal user, exiting..."
    exit 1
fi

# Test sudo; exit if wrong password or terminated via Ctrl-C.
sudo id >/dev/null; [[ $? -ne 0 ]] && exit 2

# Remove desktop file.
rm -fv ~/.local/share/applications/google-chrome.desktop

# Uninstall package.
dpkg-query -f '${binary:Package}\n' -W | grep -q '^google-chrome-stable$'

if [[ $? -eq 0 ]]; then
    set -x  # enable verbose output
    sudo apt autoremove -y --purge google-chrome-stable
    set +x  # disable verbose output
fi

# Remove apt files.
sudo rm -fv /etc/apt/sources.list.d/google-chrome.list
sudo rm -fv /etc/apt/trusted.gpg.d/google-chrome.gpg

echo "OK"

