#!/usr/bin/env bash

# Uninstall script for Brave Browser.
# https://brave.com/linux/

if [[ "$USER" == "root" ]]; then
    echo "Please run the script as a normal user, exiting..."
    exit 1
fi

# Test sudo; exit if wrong password or terminated via Ctrl-C.
sudo id >/dev/null; [[ $? -ne 0 ]] && exit 2

# Remove desktop file.
if [ -d ~/.local/share/applications ]; then
    rm -fv ~/.local/share/applications/brave-browser.desktop
fi

# Uninstall package.
dpkg-query -f '${binary:Package}\n' -W | grep -q '^brave-browser$'

if [[ $? -eq 0 ]]; then
    set -x  # enable verbose output
    sudo apt autoremove -y --purge brave-browser
    set +x  # disable verbose output
fi

# Remove apt files.
if [ -f /etc/apt/sources.list.d/brave-browser-release.list ]; then
    sudo rm -fv /etc/apt/sources.list.d/brave-browser-release.list
fi

if [ -f /etc/apt/trusted.gpg.d/brave-browser-release.gpg ]; then
    sudo rm -fv /etc/apt/trusted.gpg.d/brave-browser-release.gpg
fi

echo "OK"

