#!/usr/bin/env bash

# Uninstall script for Opera.
# https://www.ubuntuupdates.org/ppa/opera

if [[ "$USER" == "root" ]]; then
    echo "Please run the script as a normal user, exiting..."
    exit 1
fi

# Test sudo; exit if wrong password or terminated via Ctrl-C.
sudo id >/dev/null; [[ $? -ne 0 ]] && exit 2

# Remove desktop file.
rm -fv ~/.local/share/applications/opera.desktop

# Uninstall package.
dpkg-query -f '${binary:Package}\n' -W | grep -q '^opera-stable$'

if [[ $? -eq 0 ]]; then
    sudo rm -fr /usr/lib/x86_64-linux-gnu/opera/lib_extra
    sudo rm -fr /usr/lib/x86_64-linux-gnu/opera/resources/widevine_config.json
    set -x  # enable verbose output
    sudo apt autoremove -y --purge opera-stable
    set +x  # disable verbose output
fi

# Remove apt files.
sudo rm -fv /etc/apt/sources.list.d/opera-stable.list
sudo rm -fv /etc/apt/trusted.gpg.d/opera.gpg

echo "OK"

