#!/bin/bash

# Uninstall script for Chromium.
# https://github.com/ungoogled-software/ungoogled-chromium-debian

if [[ "$USER" == "root" ]]; then
    echo "Please run the script as a normal user, exiting..."
    exit 1
fi

# Test sudo; exit if wrong password or terminated via Ctrl-C.
sudo id >/dev/null; [[ $? -ne 0 ]] && exit 2

# Remove desktop file.
rm -fv ~/.local/share/applications/chromium.desktop

# Uninstall package.
dpkg-query -f '${binary:Package}\n' -W | grep -q '^ungoogled-chromium$'

if [[ $? -eq 0 ]]; then
    set -x  # enable verbose output
    sudo apt autoremove -y --purge ungoogled-chromium
    set +x  # disable verbose output
fi

# Remove apt files.
sudo rm -fv /etc/apt/sources.list.d/home-ungoogled_chromium.list
sudo rm -fv /etc/apt/trusted.gpg.d/home-ungoogled_chromium.gpg

echo "OK"

