#!/bin/bash

# Uninstall script for Brave Browser.
# https://brave.com/linux/

if [[ "$USER" == "root" ]]; then
    echo "Please run the script as a normal user, exiting..."
    exit 1
fi

# Test sudo; exit if wrong password or terminated via Ctrl-C.
sudo id >/dev/null; [[ $? -ne 0 ]] && exit 2

# Remove desktop file.
rm -fv ~/.local/share/applications/brave-browser.desktop

# Uninstall package.
dpkg --list brave-browser >/dev/null 2>&1

if [[ $? -eq 0 ]]; then
    set -x  # enable verbose output
    sudo apt autoremove -y --purge brave-browser
    set +x  # disable verbose output
fi

# Remove apt files.
sudo rm -fv /etc/apt/sources.list.d/brave-browser-release.list
sudo rm -fv /etc/apt/trusted.gpg.d/brave-browser-release.gpg

echo "OK"

